apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "paca.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "paca.componentLabels" (dict "root" . "component" "gateway") | nindent 4 }}
data:
  Caddyfile: |-
{{ .Files.Get "files/Caddyfile" | indent 4 }}
